### ISSUE TITLE
unable to compile with "smoltcp" feature

### ISSUE THREAD

**Issue by alessio-proietti** [hermitcore/rusty-hermit#168] opened 2021-11-03 11:38 UTC
Hi, it seems compilation breaks on my system when net is requested. 
Compilation is performed as per actual documentation. 

Here the note in the error :

> = note: rust-lld: error: undefined symbol: sys_netwait

my `Cargo.toml`

> cargo-features = ["edition2021"]
> 
> [package]
> name = "novembre2021"
> version = "0.1.0"
> edition = "2021"
> 
> [target.'cfg(target_os = "hermit")'.dependencies.hermit-sys]
> version = "0.1.*"
> default-features = false
> features = ["smoltcp"]
> 
> [profile.release]
> opt-level = 3
> 
> [profile.dev]
> opt-level = 1

the active toolchain:

> rustup default
> nightly-2021-08-31-x86_64-unknown-linux-gnu (default)

**Comment by sjmackenzie** [comment] 2021-11-28 13:46
I've just run into this issue, blows up at this point: https://github.com/hermitcore/rusty-hermit/blob/739f96d1114e32ec9833ed7c27fe8775502d8d2b/hermit-sys/src/net/mod.rs#L369

**Comment by mkroening** [comment] 2021-12-12 11:09
Sorry for the late reply!

I can't reproduce this issue on with [rusty-demo](https://github.com/hermitcore/rusty-demo). Is this issue resolved? If not, could you share more details for reproduction?

**Comment by sjmackenzie** [comment] 2021-12-12 14:30
Hello! 

I got the error to go away by using a git clone of this repository on my machine. I suspect if you use the published crates on crates.io you will run into the issue.

**Comment by mkroening** [comment] 2021-12-12 14:43
Using crates.io works for me. Could you try again? There was a new release a few days ago, so the issue might have been fixed in the meantime. Running `cargo update` might help if cargo does not pick up the new version.

My `Cargo.toml`:
```toml
[target.'cfg(target_os = "hermit")'.dependencies]
hermit-sys = { version = "0.1", features = ["smoltcp"] }
```

**Comment by sjmackenzie** [comment] 2021-12-12 14:48
Okay! It works well, well done! I think this issue can be closed.

**Comment by mkroening** [comment] 2021-12-12 14:53
All right! Thanks for your help!

**Closed by mkroening** 2021-12-12 14:53 UTC
